export { Home } from './Home';
export { About } from './About';
export { Skills } from './Skills';
export { Projects } from './Projects';
export { Experience } from './Experience';
export { Education } from './Education';
export { Contact } from './Contact';
export { Blog } from './Blog';
export { NotFound } from './NotFound';
